<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $results
 * @var string $userStatus
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics index');

$currentPage = $this->params()->fromQuery('page');
$limit = $this->setting('pagination_per_page', 100);
$currentUrl = $urlHelper(null, [], true);
$basePath = $this->basePath();
$resource = null;
?>

<?= $this->pageTitle(sprintf($translate('Statistics (%s total)'), $results['all']['total']), 1, $translate('Statistics')) ?>

<?= $this->partial('common/statistics-nav') ?>

<h2><?= sprintf($translate('Total Hits: %d [%d anonymous / %d identified]'),
    $results['all']['total'],
    $results['all']['anonymous'],
    $results['all']['identified'])
?></h2>
<h3><?= sprintf($translate('Today: %d [%d / %d]'),
    $results['today']['total'],
    $results['today']['anonymous'],
    $results['today']['identified'])
?></h3>

<section class="three columns alpha">
    <div class="panel">
        <h2><?= $translate('History') ?></h2>
        <ul>
        <?php foreach ($results['history'] as $label => $value): ?>
            <li><?=
                sprintf('%s: %d [%d / %d]', $label, $value['total'], $value['anonymous'], $value['identified'])
            ?></li>
        <?php endforeach; ?>
        </ul>
    </div>
</section>
<section class="four columns">
    <div class="panel">
        <h2><?= $translate('Current') ?></h2>
        <ul>
        <?php foreach ($results['current'] as $label => $value): ?>
            <li><?=
                sprintf('%s: %d [%d / %d]', $label, $value['total'], $value['anonymous'], $value['identified'])
            ?></li>
        <?php endforeach; ?>
        </ul>
    </div>
</section>
<section class="three columns omega">
    <div class="panel">
        <h2><?= $translate('Rolling Period') ?></h2>
        <ul>
        <?php foreach ($results['rolling'] as $label => $value): ?>
            <li><?=
                sprintf('%s: %d [%d / %d]', $label, $value['total'], $value['anonymous'], $value['identified'])
            ?></li>
        <?php endforeach; ?>
        </ul>
    </div>
</section>
<?php if (isset($results['most_viewed_pages'])): ?>
<section class="ten columns alpha omega">
    <div class="panel">
        <h2><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-page']) ?>"><?= $translate('Most viewed public pages') ?></a></h2>
        <?php if (empty($results['most_viewed_pages'])): ?>
        <p><?= $translate('None') ?></p>
        <?php else: ?>
        <ol>
        <?php foreach ($results['most_viewed_pages'] as $position => $stat): ?>
            <li><?= sprintf($translate('%s (%d views [%d / %d])'),
                '<a href="' . $escapeAttr($basePath . $stat->hitUrl()) . '">' . $escape($stat->hitUrl()) . '</a>',
                $stat->totalHits(),
                $stat->totalHits('anonymous'),
                $stat->totalHits('identified'))
            ?></li>
        <?php endforeach; ?>
        </ol>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
<?php if (isset($results['most_viewed_resources'])): ?>
<section class="ten columns alpha omega">
    <div class="panel">
        <h2><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-resource']) ?>"><?= $translate('Most viewed public records') ?></a></h2>
        <?php if (empty($results['most_viewed_resources'])): ?>
        <p><?= $translate('None') ?></p>
        <?php else: ?>
        <ol>
        <?php foreach ($results['most_viewed_resources'] as $position => $stat): ?>
            <li><?= sprintf($translate('%s (%d views [%d / %d])'),
                ($resource = $stat->entityResource()) ? $resource->linkPretty() : sprintf('%s #%s (unavailable)', $translate($stat->entityName()), $stat->entityName()),
                $stat->totalHits(),
                $stat->totalHits('anonymous'),
                $stat->totalHits('identified'))
            ?></li>
        <?php endforeach; ?>
        </ol>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
<?php if (isset($results['most_viewed_item_sets'])): ?>
<section class="ten columns alpha omega">
    <div class="panel">
        <h2><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-item-set']) ?>"><?= $translate('Most viewed public collections') ?></a></h2>
        <?php if (empty($results['most_viewed_item_sets'])): ?>
        <p><?= $translate('None') ?></p>
        <?php else: ?>
        <ol>
        <?php foreach ($results['most_viewed_item_sets'] as $position => $stat): ?>
            <li><?= sprintf($translate('%s (%d views [%d / %d])'),
                ($resource = $stat->entityResource()) ? $resource->linkPretty() : sprintf('%s #%s (unavailable)', $translate($stat->entityName()), $stat->entityName()),
                $stat->totalHits(),
                $stat->totalHits('anonymous'),
                $stat->totalHits('identified'))
            ?></li>
        <?php endforeach; ?>
        </ol>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
<?php if (isset($results['most_viewed_downloads'])): ?>
<section class="ten columns alpha omega">
    <div class="panel">
        <h2><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-download']) ?>"><?= $translate('Most downloaded files') ?></a></h2>
        <?php if (empty($results['most_viewed_downloads'])): ?>
        <p><?= $translate('None') ?></p>
        <?php else: ?>
        <ol>
        <?php foreach ($results['most_viewed_downloads'] as $position => $stat): ?>
            <li><?= sprintf($translate('%s (%d downloads [%d / %d])'),
                '<a href="' . $escapeAttr($basePath . $stat->hitUrl()) . '">' . $escape($stat->hitUrl()) . '</a>',
                $stat->totalHits(),
                $stat->totalHits('anonymous'),
                $stat->totalHits('identified'))
            ?></li>
        <?php endforeach; ?>
        </ol>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
<?php if (isset($results['most_frequent_fields'])):
    $labels = [
        'referrer' => $translate('Most frequent external referrers'),
        'query' =>$translate('Most frequent queries'),
        'accept_language' => $translate('Most frequent accepted languages'),
        'user_agent' => $translate('Most frequent browsers'),
    ];
    foreach ($results['most_frequent_fields'] as $field => $result): ?>
<section class="ten columns alpha omega">
    <div class="panel">
        <h2><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-field'], ['query' => ['field' => $field]]) ?>"><?= $labels[$field]; ?></a></h2>
        <?= $this->partial('common/statistics-most-frequents', [
            'results' => $result,
            'field' => $field,
        ]) ?>
    </div>
</section>
    <?php endforeach;
endif; ?>
