[routes]
stats_download.type = "Zend_Controller_Router_Route_Regex"
stats_download.route = "download/files/([^/]+)/(.*)"
stats_download.defaults.module = "stats"
stats_download.defaults.controller = "download"
stats_download.defaults.action = "files"
stats_download.map.1 = "type"
stats_download.map.2 = "filename"

stats_download_files.type = "Zend_Controller_Router_Route_Regex"
stats_download_files.route = "stats/download/files/([^/]+)/(.*)"
stats_download_files.defaults.module = "stats"
stats_download_files.defaults.controller = "download"
stats_download_files.defaults.action = "files"
stats_download_files.map.1 = "type"
stats_download_files.map.2 = "filename"
