<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Stats\Api\Representation\StatRepresentation[] $result
 * @var string $field
 * @var string $userStatus
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
?>

<?php if (empty($result)): ?>

<p><?= $translate('None') ?></p>

<?php else: ?>

<ol>
    <?php foreach ($result as $position => $stat): ?>
    <li><?= sprintf($translate('%s (%d views)'), $stat->field($field), $stat->totalHits($userStatus)) ?></li>
    <?php endforeach; ?>
</ol>

<?php endif; ?>
