<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $results
 * @var string $field
 * @var string $userStatus
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
?>

<?php if (empty($results)): ?>

<p><?= $translate('None') ?></p>

<?php else: ?>

<ol>
    <?php foreach ($results as $position => $result): ?>
    <li><?= sprintf($translate('%s (%d views)'), $result[$field], $result['hits']) ?></li>
    <?php endforeach; ?>
</ol>

<?php endif; ?>
