<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Stats\Api\Representation\StatRepresentation $stat
 * @var string $type
 * @var string $userStatus
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
?>

<div class="stats-stat">
    <p><?php
    if ($type === 'download'):
        if (empty($stat)):
            echo $translate('Not downloaded');
        else:
            echo sprintf($translate('Position: %s (%s downloads)'),
                '<span class="stats-position">' . $stat->position($userStatus) . '</span>',
                '<span class="stats-hits">' . $stat->totalHits($userStatus) . '</span>'
            );
        endif;
    else:
        if (empty($stat)):
            echo $translate('Not viewed');
        else:
            echo sprintf($translate('Position: %s (%s views)'),
                '<span class="stats-position">' . $stat->position($userStatus) . '</span>',
                '<span class="stats-hits">' . $stat->totalHits($userStatus) . '</span>'
            );
        endif;
    endif;
    ?></p>
</div>
