<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

// @todo Use laminas navigation menu.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');

$sectionNavs = [];
if ($this->userIsAllowed('Statistics\Controller\Summary', 'index')) {
    $sectionNavs[$urlHelper('admin/statistics')] = $translate('Summary');
}
if ($this->userIsAllowed('Statistics\Controller\Browse', 'by-page')) {
    $sectionNavs[$urlHelper('admin/statistics/default', ['action' => 'by-page'])] = $translate('By page');
    $sectionNavs[$urlHelper('admin/statistics/default', ['action' => 'by-resource'])] = $translate('By resource');
    $sectionNavs[$urlHelper('admin/statistics/default', ['action' => 'by-download'])] = $translate('By download');
    $sectionNavs[$urlHelper('admin/statistics/default', ['action' => 'by-field'])] = $translate('By field');
    $sectionNavs[$urlHelper('admin/statistics/default', ['action' => 'by-item-set'])] = $translate('By item set');
}
if (empty($sectionNavs)) return;

$currentUrl = $urlHelper(null, [], true);
// Fix summary url.
if (substr($currentUrl, -6) === '/index') $currentUrl = substr($currentUrl, 0, -6);
?>

<nav class="section-nav">
    <ul class="navigation">
        <?php foreach ($sectionNavs as $url => $label): ?>
        <li<?= $currentUrl === $url ? ' class="active"' : '' ?>">
            <a href="<?= $url ?>"><?= $escape($label) ?></a>
        </li>
        <?php endforeach; ?>
    </ul>
</nav>
