<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Stats\Api\Representation\StatRepresentation[] $resources
 * @var \Stats\Api\Representation\StatRepresentation[] $stats
 * @var \Stats\Api\Representation\HitRepresentation[] $hits
 * @var string $userStatus
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()->prependStylesheet($assetUrl('css/stats.css', 'Stats'));

$this->htmlElement('body')->appendAttribute('class', 'stats browse');
?>

<?= $this->pageTitle($translate('Stats'), 1, $translate('By Collection')) ?>

<?= $this->partial('common/stats-nav') ?>

<form method="get">
    <select name="year">
        <option value=""><?= $translate('All years') ?></option>
        <?php foreach ($years as $year): ?>
            <option value="<?= $year ?>" <?php if ($yearFilter == $year): ?>selected="selected"<?php endif; ?>><?= $year ?></option>
        <?php endforeach; ?>
    </select>

    <?php $months = [
        $translate('January'),
        $translate('February'),
        $translate('March'),
        $translate('April'),
        $translate('May'),
        $translate('June'),
        $translate('July'),
        $translate('August'),
        $translate('September'),
        $translate('October'),
        $translate('November'),
        $translate('December'),
    ]; ?>
    <select name="month">
        <option value=""><?= $translate('All months') ?></option>
        <?php foreach ($months as $i => $month): ?>
            <option value="<?= $i + 1 ?>"<?php if ($monthFilter == $i + 1): ?>selected="selected"<?php endif; ?>><?= $month ?></option>
        <?php endforeach; ?>
    </select>
    <button type="submit"><?= $translate('Filter') ?></button>
</form>

<?php if (count($stats)): ?>
    <table class="stats-table">
    <thead>
        <tr>
            <?php
            $browseHeadings[$translate('Item set')] = 'item-set';
            $browseHeadings[$translate('Hits')] = 'hits';
            echo browse_sort_links($browseHeadings, array('link_tag' => 'th scope="col"', 'list_tag' => ''));
            ?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($hits as $position => $hit): ?>
        <tr class="stats-stat <?= $position % 2 === 0 ? 'odd' : 'even' ?>">
            <td class="stats-field"><?= $hit->field('item-set') ?></td>
            <td class="stats-hits"><?= $hit->totalPage() ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
    </table>
<?php else: ?>
    <br class="clear" />
    <?php $totalHits = $this->api()->search('hits')->getTotalResults(); ?>
    <?php if (!$totalHits): ?>
        <h2><?= $translate('There is no hit yet.') ?></h2>
    <?php else: ?>
        <p><?= $translate('The query searched %s hits and returned no results.', $totalHits); ?></p>
        <p><a href="<?= $this->url('admin/stats/default', ['action' => 'by-collection'], true) ?>"><?= $translate('See all stats.') ?></a></p>
    <?php endif; ?>
<?php endif; ?>
