<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $results
 * @var string $type "field"
 * @var string $field
 * @var string $labelField
 * @var string $totalHits
 * @var string $totalNotEmpty
 * @var string $userStatus
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$totalResults = $this->pagination()->getPaginator()->getTotalCount();
$currentUrl = $urlHelper(null, [], true);
?>

<?= $this->pageTitle(sprintf($translate('Statistics (%s total)'), $totalResults), 1, $translate('Statistics')) ?>

<?= $this->partial('common/statistics-nav') ?>

<p>
    <strong><?= sprintf($translate('By %s (%s)'), $labelField, $this->statistic()->humanUserStatus($userStatus)) ?></strong>
    <em><?= sprintf($translate('[%d filled values / %d total hits]'), $totalNotEmpty, $totalHits) ?></em>
</p>

<?php if ($totalResults): ?>
<div class="browse-controls">
    <?= $pagination = $this->pagination() ?>
    <?= $this->partial('common/statistics-quick-filters') ?>
    <?php //= $this->sortSelector($sortHeadings) ?>
</div>
<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $currentUrl . '?sort_by=' . $field ?>"><?= $labelField ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=hits' ?>"><?= $translate('Hits') ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=hits' ?>"><?= $translate('Percent') ?></a>
            </th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($results as $position => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $result[$field] ?></td>
            <td class="statistics-hits"><?= $result['hits'] ?></td>
            <td class="statistics-percent"><?= round($result['hits'] * 100 / $totalNotEmpty, 1) ?>%</td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
    <?= $pagination ?>
<?php else: ?>
    <br class="clear" />
    <div class="no-resources">
    <?php if (!$totalHits): ?>
        <p><?= $translate('There is no hit yet.') ?></p>
    <?php else: ?>
        <p><?= $translate('The query searched %s hits and returned no results.', $totalHits) ?></p>
        <p><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-' . $type], true) ?>"><?= $translate('See all statistics.') ?></a></p>
    <?php endif; ?>
    </div>
<?php endif; ?>
