<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Statistics\Api\Representation\StatRepresentation[] $resources
 * @var \Statistics\Api\Representation\StatRepresentation[] $stats
 * @var \Statistics\Api\Representation\HitRepresentation[] $hits
 * @var string $userStatus
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()->prependStylesheet($assetUrl('css/stats.css', 'Stats'));

$this->htmlElement('body')->appendAttribute('class', 'stats browse');

// TODO Add total results from pagination.

// TODODOODODODODODOO

$totalResults = 0;
?>

<?= $this->pageTitle($translate('Stats'), 1, sprintf($translate('Stats (%s total)'), $totalResults)) ?>

<?= $this->partial('common/statistics-nav') ?>

<p>
    <strong><?= $translate('By %s (%s)', $label_field, $this->stats()->human_user_status($user_status)); ?></strong>
    <em><?php echo ' ' . $translate('[%d filled values / %d total hits]', $total_not_empty, $total_hits); ?></em>
</p>

<?php echo common('quick-filters', array('stats_type' => $stats_type)); ?>

<?php if ($total_results):
    echo pagination_links();
    ?>
    <table class="statistics-table">
    <thead>
        <tr>
            <?php
            $browseHeadings[$label_field] = $field;
            $browseHeadings[$translate('Hits')] = 'hits';
            $browseHeadings['%'] = 'hits';
            echo browse_sort_links($browseHeadings, array('link_tag' => 'th scope="col"', 'list_tag' => ''));
            ?>
        </tr>
    </thead>
    <tbody>
<?php $key = 0; ?>
<?php foreach ($hits as $position => $hit): ?>
        <tr class="statistics-stat <?php if (++$key % 2 == 1) echo 'odd'; else echo 'even'; ?>">
            <td class="statistics-field"><?php echo $hit[$field]; ?></td>
            <td class="statistics-hits"><?php echo $hit['hits']; ?></td>
            <td class="statistics-percent"><?php echo round($hit['hits'] * 100 / $total_not_empty, 1); ?>%</td>
        </tr>
<?php endforeach; ?>
    </tbody>
    </table>
    <?php echo pagination_links(); ?>
<?php else: ?>
    <br class="clear" />
    <?php if (total_records('Hit') == 0): ?>
        <h2><?= $translate('There is no hit yet.'); ?></h2>
    <?php else: ?>
        <p><?= $translate('The query searched %s hits and returned no results.', total_records('Hit')); ?></p>
        <p><a href="<?php echo url('admin/statistics/browse/by-' . $stats_type); ?>"><?= $translate('See all stats.'); ?></a></p>
    <?php endif; ?>
<?php endif; ?>
    <?php echo common('quick-filters', array('stats_type' => $stats_type)); ?>
