<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $results
 * @var string $type "item-set"
 * @var array $hits
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Stats'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$currentUrl = $urlHelper(null, [], true);
?>

<?= $this->pageTitle($translate('By item set'), 1, $translate('Statistics')) ?>

<?= $this->partial('common/statistics-nav') ?>

<form method="get">
    <select name="year">
        <option value=""><?= $translate('All years') ?></option>
        <?php foreach ($years as $year): ?>
            <option value="<?= $year ?>"<?= $yearFilter == $year ? ' selected="selected"' : '' ?>><?= $year ?></option>
        <?php endforeach; ?>
    </select>

    <?php $months = [
        $translate('January'),
        $translate('February'),
        $translate('March'),
        $translate('April'),
        $translate('May'),
        $translate('June'),
        $translate('July'),
        $translate('August'),
        $translate('September'),
        $translate('October'),
        $translate('November'),
        $translate('December'),
    ]; ?>
    <select name="month">
        <option value=""><?= $translate('All months') ?></option>
        <?php foreach ($months as $i => $month): ?>
            <option value="<?= $i + 1 ?>"<?= $monthFilter == $i + 1 ? ' selected="selected"' : '' ?>><?= $month ?></option>
        <?php endforeach; ?>
    </select>
    <button type="submit"><?= $translate('Filter') ?></button>
</form>

<?php if (count($results)): ?>
<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $currentUrl . '?sort_by=item-set' ?>"><?= $translate('Item set') ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=hits' ?>"><?= $translate('Hits') ?></a>
            </th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($results as $position => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $result['item-set'] ?></td>
            <td class="statistics-hits"><?= $result['hits'] ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
    <br class="clear" />
    <?php $totalHits = $this->api()->search('hits')->getTotalResults(); ?>
    <?php if (!$totalHits): ?>
        <h2><?= $translate('There is no hit yet.') ?></h2>
    <?php else: ?>
        <p><?= sprintf($translate('The query searched %s hits and returned no results.'), $totalHits) ?></p>
        <p><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-item-set'], true) ?>"><?= $translate('See all statistics.') ?></a></p>
    <?php endif; ?>
<?php endif; ?>
